server:
  tomcat:
    mbeanregistry:
      enabled: true
    threads:
      max: ${TOMCAT_MAX_THREADS}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: ${HIKARI_POOL_SIZE}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  profiles:
    active: dev

  session:
    store-type: redis
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:}

logging:
  level:
    org.hibernate.SQL: debug

file:
  dir: ./uploads/

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000}

cloud:
  aws:
    s3:
      bucket: community-image-545122900064-ap-northeast-2-an
      video-bucket: podcast-raw-data-545122900064-ap-northeast-2-an
    stack.auto: false
    region.static: ap-northeast-2

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: my-spring-app
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.95, 0.99
